//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongVienEntityFramwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongVien
    {
        public string maPV { get; set; }
        public string tenPV { get; set; }
        public string GT { get; set; }
        public string soDT { get; set; }
        public Nullable<System.DateTime> ngayVL { get; set; }
        public Nullable<double> PC { get; set; }
        public Nullable<int> gioLT { get; set; }
        public string loaiPV { get; set; }
        public Nullable<double> Luong { get; set; }
    }
}
